/*
 * Universidad Politecnica de San Luis Potosi
 * Programación III
 * Programación Orientada a Objetos
 */
package s10p04paintpaleta;
import java.awt.*;

/**
 *
 * @author Saul Cervantes Candia
 */
public class PaintPaleta extends javax.swing.JFrame {

    public PaintPaleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        btnRojo = new javax.swing.JRadioButton();
        btnAzul = new javax.swing.JRadioButton();
        btnVerde = new javax.swing.JRadioButton();
        btnAmarillo = new javax.swing.JRadioButton();
        btnMagenta = new javax.swing.JRadioButton();
        btnBlanco = new javax.swing.JRadioButton();
        deslizante = new javax.swing.JSlider();
        tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        buttonGroup1.add(btnRojo);
        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAzul);
        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnVerde);
        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAmarillo);
        btnAmarillo.setText("Amarillo");
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMagenta);
        btnMagenta.setText("Magenta");
        btnMagenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagentaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBlanco);
        btnBlanco.setText("Borrar");
        btnBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancoActionPerformed(evt);
            }
        });

        deslizante.setMaximum(250);
        deslizante.setMinimum(10);
        deslizante.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizanteStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deslizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAzul)
                        .addGap(44, 44, 44)
                        .addComponent(btnVerde)
                        .addGap(31, 31, 31)
                        .addComponent(btnAmarillo)
                        .addGap(41, 41, 41)
                        .addComponent(btnMagenta)
                        .addGap(28, 28, 28)
                        .addComponent(btnBlanco)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRojo)
                    .addComponent(btnAzul)
                    .addComponent(btnVerde)
                    .addComponent(btnAmarillo)
                    .addComponent(btnMagenta)
                    .addComponent(btnBlanco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deslizante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deslizanteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizanteStateChanged
        tf.setText(Integer.toString(deslizante.getValue()));
    }//GEN-LAST:event_deslizanteStateChanged

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        Graphics papel = panel.getGraphics();
        Color color = Color.WHITE;
        int n = deslizante.getValue();
        
        int x = evt.getX();
        int y = evt.getY();
        
        if(btnRojo.isSelected()){
            color = Color.RED;
        }
        if(btnAzul.isSelected()){
            color = Color.BLUE;
        }
        if(btnVerde.isSelected()){
            color = Color.GREEN;
        }
        if(btnAmarillo.isSelected()){
            color = Color.YELLOW;
        }
        if(btnMagenta.isSelected()){
            color = Color.MAGENTA;
        }
        if(btnBlanco.isSelected()){
            color = Color.WHITE;
            //papel.setColor(Color.WHITE);
        }
        
        papel.setColor(color);
        papel.fillOval(x, y, n, n);
    }//GEN-LAST:event_panelMouseDragged

    private void panelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseMoved

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnAmarilloActionPerformed

    private void btnMagentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagentaActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnMagentaActionPerformed

    private void btnBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancoActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
    }//GEN-LAST:event_btnBlancoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.JRadioButton btnAzul;
    private javax.swing.JRadioButton btnBlanco;
    private javax.swing.JRadioButton btnMagenta;
    private javax.swing.JRadioButton btnRojo;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSlider deslizante;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
