/*
 * Universidad Politecnica de San Luis Potosi
 * Programación III
 * Programación Orientada a Objetos
 */
package s09p05radiobotonpaleta;

import java.awt.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author Saul Cervantes Candia
 */
public class RadioBotonPaleta extends javax.swing.JFrame {
    //Image foto;
    public RadioBotonPaleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        jRadio4 = new javax.swing.JRadioButton();
        jRadio5 = new javax.swing.JRadioButton();
        jRadio6 = new javax.swing.JRadioButton();
        jRadio3 = new javax.swing.JRadioButton();
        jRadio2 = new javax.swing.JRadioButton();
        jRadio1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadio4);
        jRadio4.setText("Imagen1");
        jRadio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio5);
        jRadio5.setText("Imagen2");
        jRadio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio6);
        jRadio6.setText("Imagen3");
        jRadio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio3);
        jRadio3.setText("Cuadrado");
        jRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio2);
        jRadio2.setText("Circulo");
        jRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio1);
        jRadio1.setText("Linea");
        jRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadio1)
                    .addComponent(jRadio4))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadio2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio3)
                    .addComponent(jRadio6))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio3)
                    .addComponent(jRadio2)
                    .addComponent(jRadio1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio4)
                    .addComponent(jRadio5)
                    .addComponent(jRadio6))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1ActionPerformed
        //Limpiar panel
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        papel.setColor(Color.RED);
        papel.drawLine(50, 50, 150, 150);
    }//GEN-LAST:event_jRadio1ActionPerformed

    private void jRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2ActionPerformed
        //Limpiar panel
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        papel.setColor(Color.RED);
        papel.fillOval(50, 50, 150, 150);
    }//GEN-LAST:event_jRadio2ActionPerformed

    private void jRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio3ActionPerformed
        //Limpiar panel
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        papel.setColor(Color.RED);
        papel.fillRect(50, 50, 150, 150);
    }//GEN-LAST:event_jRadio3ActionPerformed

    private void jRadio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio4ActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        ImageIcon foto;
        foto = new ImageIcon(getClass().getResource("/img/1.jpg"));
        papel.drawImage(foto.getImage(), 0, 0, 300, 300, null);
    }//GEN-LAST:event_jRadio4ActionPerformed

    private void jRadio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio5ActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        ImageIcon foto;
        foto = new ImageIcon(getClass().getResource("/img/2.jpg"));
        papel.drawImage(foto.getImage(), 0, 0, 300, 300, null);
    }//GEN-LAST:event_jRadio5ActionPerformed

    private void jRadio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio6ActionPerformed
        Graphics papel = panel.getGraphics();
        papel.setColor(Color.WHITE);
        papel.fillRect(0, 0, 350, 300);
        ImageIcon foto;
        foto = new ImageIcon(getClass().getResource("/img/3.jpg"));
        papel.drawImage(foto.getImage(), 0, 0, 300, 300, null);
    }//GEN-LAST:event_jRadio6ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadio1;
    private javax.swing.JRadioButton jRadio2;
    private javax.swing.JRadioButton jRadio3;
    private javax.swing.JRadioButton jRadio4;
    private javax.swing.JRadioButton jRadio5;
    private javax.swing.JRadioButton jRadio6;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
