/*
 * Universidad Politecnica de San Luis Potosi
 * Programación III
 * Programación Orientada a Objetos
 */
package s12p03excepcionesgraficaspaleta;

import javax.swing.JOptionPane;

/**
 *
 * @author Saul Cervantes Candia
 */
public class ExcepcionesGraficasPaleta extends javax.swing.JFrame {

    /**
     * Creates new form ExcepcionesGraficasPaleta
     */
    public ExcepcionesGraficasPaleta() {
        initComponents();
        this.setTitle("Excepciones Propias");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        tfResultado.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfN1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfN2 = new javax.swing.JTextField();
        btnSum = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        tfResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número 1");

        jLabel2.setText("Número 2");

        btnSum.setText("Sumar");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        btnRes.setText("Resta");
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });

        btnMult.setText("Multiplicacion");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnDiv.setText("Division");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfN1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(tfN2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnSum)
                        .addGap(26, 26, 26)
                        .addComponent(btnRes)
                        .addGap(18, 18, 18)
                        .addComponent(btnMult)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiv)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79)
                .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSum)
                    .addComponent(btnRes)
                    .addComponent(btnMult)
                    .addComponent(btnDiv))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        try{
            String t1 = tfN1.getText();
            float n1 = Float.parseFloat(t1);

            float n2 = Float.parseFloat(tfN2.getText());

            if(btnSum == evt.getSource()){
                tfResultado.setText(Float.toString((n1+n2)));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese numero entero o decimal "+e);
            tfN1.setText("");
            tfN2.setText("");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, er);
            System.out.println("Error "+er);
        }
    }//GEN-LAST:event_btnSumActionPerformed

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        try{
            String t1 = tfN1.getText();
            float n1 = Float.parseFloat(t1);

            float n2 = Float.parseFloat(tfN2.getText());
            
            if(btnRes == evt.getSource()){
                tfResultado.setText(Float.toString((n1-n2)));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese numero entero o decimal "+e);
            tfN1.setText("");
            tfN2.setText("");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, er);
            System.out.println("Error "+er);
        }
    }//GEN-LAST:event_btnResActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        try{
            String t1 = tfN1.getText();
            float n1 = Float.parseFloat(t1);

            float n2 = Float.parseFloat(tfN2.getText());

            if(btnMult == evt.getSource()){
                tfResultado.setText(Float.toString((int)(n1*n2)));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese numero entero o decimal "+e);
            tfN1.setText("");
            tfN2.setText("");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, er);
            System.out.println("Error "+er);
        }
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        try{
            String t1 = tfN1.getText();
            float n1 = Float.parseFloat(t1);

            float n2 = Float.parseFloat(tfN2.getText());

            if(btnDiv == evt.getSource()){
                tfResultado.setText(Float.toString((n1/n2)));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese numero entero o decimal "+e);
            tfN1.setText("");
            tfN2.setText("");
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, er);
            System.out.println("Error "+er);
        }
    }//GEN-LAST:event_btnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfN1;
    private javax.swing.JTextField tfN2;
    private javax.swing.JTextField tfResultado;
    // End of variables declaration//GEN-END:variables
}
